# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_remove_author_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, to='myApp.Student'),
        ),
    ]
